document.querySelectorAll(`[data-index="0"]`)[0].click()
document.querySelectorAll(`[data-index="1"]`)[1].click()

document.querySelectorAll(`[data-index="2"]`)[3].click()
document.querySelectorAll(`[data-index="2"]`)[4].click()
document.querySelectorAll(`[data-index="3"]`)[5].click()
document.querySelectorAll(`[data-index="1"]`)[6].click()
document.querySelectorAll(`[data-index="2"]`)[7].click()
document.querySelectorAll(`[data-index="3"]`)[8].click()
document.querySelectorAll(`[data-index="3"]`)[9].click()
document.querySelectorAll(`[data-index="2"]`)[10].click()
document.querySelectorAll(`[data-index="2"]`)[11].click()
document.querySelectorAll(`[data-index="2"]`)[12].click()
document.querySelectorAll(`[data-index="1"]`)[13].click()
document.querySelectorAll(`[data-index="2"]`)[14].click()